parquet reader for import update and replace
dolthub/dolt pull request #2437
Opened 2021-11-29 19:42 UTC by jennifersp

Added parquet reader for import update and import replace only, for import create, schema file is required.

2021-11-30 19:55 UTC, VinaiRachakonda requested changes
I want to review this pr again once the Time changes are done

2021-11-30 19:55 UTC, VinaiRachakonda commented on go/cmd/dolt/commands/tblcmds/import.go
> +				doltRow[i] = strconv.Itoa(int(doltRow[i].(int8)))
Have two cases. One from int8 and the other for string. No need to do an additional string conversion. The int8 can be left alone. The boolean type in the sqlengine should process it accordingly.

2021-11-30 19:55 UTC, VinaiRachakonda commented on go/libraries/doltcore/schema/typeinfo/time.go
> +		val = v.(int64)
This line of code doesn't make sense. Even if v is already an int64 it should still be marshalled appropriately.

2021-11-30 19:55 UTC, VinaiRachakonda commented on go/libraries/doltcore/table/typed/parquet/reader.go
> +		// table.Values, table.RepetitionLevels, table.DefinitionLevels, nil
Either give a more detailed comment on what these things mean or delete.

2021-11-30 19:55 UTC, VinaiRachakonda commented on go/libraries/doltcore/table/typed/parquet/reader.go
> +	data := make(map[string][]interface{})
Having all the column in memory like this could be a problem in the future. Please leave a TODO

2021-11-30 19:55 UTC, VinaiRachakonda commented on go/libraries/doltcore/table/typed/parquet/writer.go
> +					return fmt.Errorf("could not get row value")
need a more expressive error

2021-12-01 00:42 UTC, andrew-wm-arthur approved these changes

2021-12-01 00:44 UTC, merged