add \G vertical query format
dolthub/dolt pull request #2593
Opened 2022-01-10 22:43 UTC by jennifersp

2022-01-11 00:49 UTC, VinaiRachakonda commented
At first glance this needs more tests with different data types and commands

2022-01-11 02:01 UTC, VinaiRachakonda requested changes

2022-01-11 02:01 UTC, VinaiRachakonda commented on go/cmd/dolt/commands/sql.go
>  		if matches := delimiterRegex.FindStringSubmatch(query); len(matches) == 3 {
You might have to modify this regex based on the line terminator instead of directly calling TrimSuffix

2022-01-11 02:01 UTC, VinaiRachakonda commented on go/cmd/dolt/commands/sql.go
> +	returnFormat := se.GetReturnFormat()
I actually want you to use a set of regexes and back track down to the correct returnFormat

2022-01-11 04:08 UTC, VinaiRachakonda commented on integration-tests/bats/sql.bats
> +@test "sql: query return format check" {
I would also like to see an expect file test running through different line terminators

2022-01-11 22:34 UTC, jennifersp commented on go/cmd/dolt/commands/sql.go
> +	returnFormat := se.GetReturnFormat()
i was not able to reproduce this issue

2022-01-12 21:15 UTC, VinaiRachakonda commented on go/cmd/dolt/commands/sqlserver/sqlclient.go
> +		LineTerminators: []string{";", "\\g", "\\G"},
Is this variable useful anymore?

2022-01-12 21:22 UTC, VinaiRachakonda approved these changes
Looks good. I'm not sure how useful the lineTerminators variable. Please check in more tests with SELECT commands, JSON Types, and any other ways you think you can break your formatting code before merging

2022-01-18 20:02 UTC, merged