Fix dolt diff --limit
dolthub/dolt pull request #4116
Opened 2022-08-17 14:54 UTC by abmyii

Closes #4078.

2022-08-17 16:06 UTC, timsehn commented
Needs at least a single bats test that tests undefined limit, limit 0, and limit > 1.

2022-08-17 16:07 UTC, abmyii commented
> Needs at least a single bats test that tests undefined limit, limit 0, and limit > 1.

Sure, will do.

2022-08-17 16:29 UTC, abmyii commented
> Needs at least a single bats test that tests undefined limit, limit 0, and limit > 1.

Done. Might have gone a bit overboard though!

2022-08-17 16:37 UTC, abmyii commented
Right now limit 0 does nothing (shows the entire diff). Would it be preferable if it showed no rows (empty tables)?
e.g.
```
+---+----+----+----+----+----+----+
|   | pk | c1 | c2 | c3 | c4 | c5 |
+---+----+----+----+----+----+----+
+---+----+----+----+----+----+----+
```

2022-08-17 16:42 UTC, timsehn commented
Seems like empty is the right approach.

2022-08-19 00:56 UTC, timsehn commented
@abmyii you want us to finish this off for you? Or will you write that one last test?

2022-08-19 01:06 UTC, timsehn requested changes

2022-08-19 01:06 UTC, timsehn commented on integration-tests/bats/diff.bats
> +    [[ "$output" =~ "+++ b/test2 @" ]] || false
```suggestion
    [[ "$output" =~ "+++ b/test2 @" ]] || false
    
    run dolt diff --limit
    [ "$status" -ne 0 ]
```

2022-08-19 09:29 UTC, abmyii commented on integration-tests/bats/diff.bats
> +    [[ "$output" =~ "+++ b/test2 @" ]] || false
Ah, I missed that one - thanks!

2022-08-19 16:06 UTC, timsehn approved these changes
This looks good. @fulghum can you get it merged in. I think it needs `repo_format`

2022-08-19 22:23 UTC, fulghum commented
Nice work @abmyii! Thanks for taking the time to contribute this fix. 🙏 

I believe the `Format PR` check doesn't run successfully in PRs from forks, but I see everything else is looking green, so I'll go ahead and merge this one in and we'll get it out in our next release.

2022-08-19 22:24 UTC, merged