Added database collation support
dolthub/dolt pull request #4629
Opened 2022-10-26 18:07 UTC by Hydrocharged

This allows setting the database collation, such that all newly created tables within a database (that do not explicitly set their collation) will inherit the database collation.

Builds on
* https://github.com/dolthub/vitess/pull/199
* https://github.com/dolthub/go-mysql-server/pull/1351

Fixes
* https://github.com/dolthub/dolt/issues/4170

2022-10-26 18:08 UTC, Hydrocharged commented
@andrew-wm-arthur Tests are failing. I know what's wrong, fixing it is just non-trivial. Ignore the failures for now (they're on the GMS side of things) and review the PR as though it's all succeeding.

2022-10-27 04:43 UTC, andrew-wm-arthur commented
I think this warrants a conversation about how we store database-level schema info. It's not clear to me if this should be written to the `datas.Database` or to the `doltdb.RootValue`

2022-10-28 16:41 UTC, andrew-wm-arthur approved these changes
LGTM!

2022-10-28 22:38 UTC, timsehn commented
You should unskip the bats test for this one:

https://github.com/dolthub/dolt/blob/f028cc43da2782d67f2da675a019de70144a837d/integration-tests/bats/sql-charsets-collations.bats#L43

2022-10-28 22:39 UTC, timsehn requested changes
Also unskip the bats test!

2022-10-31 14:48 UTC, merged