New `@@dolt_sql_user_is_committer` system variable to use SQL user as Dolt commit author
dolthub/dolt pull request #6025
Opened 2023-05-24 21:22 UTC by fulghum

Adds a new `@@dolt_sql_user_is_committer` system variable that uses the current SQL user for the Dolt commit author, instead of the `dolt config` configured user information.

Fixes https://github.com/dolthub/dolt/issues/5607

2023-05-24 21:37 UTC, zachmu approved these changes
LGTM

2023-05-24 22:43 UTC, timsehn commented
As discussed, it makes sense to just make this the default with no config option to change.

2023-05-24 22:44 UTC, timsehn requested changes
We should make this the default with no option to change.

2023-05-25 01:02 UTC, fulghum commented
> We should make this the default with no option to change.

I agree. I got the tests cleaned up and merged those changes back into this PR. Once they pass, this should be good to go.

2023-05-25 15:36 UTC, merged