Synchronize the two queryist implementations
dolthub/dolt pull request #6050
Opened 2023-05-26 23:39 UTC by PavelSafronov

Synchronize the two queryist implementations so they produce the same results.

- add a MySQL iterator that returns properly typed MySQL data
- add a SqlEngine iterator that returns matching MySQL data
- update BATS tests that are "broken" by this change

This change fixes https://github.com/dolthub/dolt/issues/6044

2023-05-27 01:42 UTC, timsehn commented
This is cool work coming out of merging these two paths

2023-05-30 16:37 UTC, macneale4 requested changes
Thanks for going deep on this! This is pretty high risk. Need lots of tests, or I need to be convinced that we have existing tests which cover all of the crazy ways schema's can be different. Given all the logic in these translation laters, we could get this very wrong.

2023-05-30 16:37 UTC, macneale4 commented on go/cmd/dolt/commands/mysql_rows_iter.go
> +}
Where is 'types' ever use once the object is constructed? It looks like you never use it, so I wouldn't bother putting it in the struct.

2023-05-30 16:37 UTC, macneale4 commented on go/cmd/dolt/commands/mysql_rows_iter.go
> +func scanResultRow(results *dsql.Rows, cols []*dsql.ColumnType) (sql.Row, error) {
You're going to need a lot of tests for this to convince me it's right. This feels like a lot of code what we could get wrong.

2023-05-30 16:37 UTC, macneale4 commented on go/cmd/dolt/commands/mysql_rows_iter.go
> +}
Why so few? What's the thinking on this specific set.

2023-06-01 16:34 UTC, macneale4 requested changes

2023-06-01 16:34 UTC, macneale4 commented on go/cmd/dolt/commands/sql_engine_queryist.go
> +			Type:     types.LongText,
I don't understand this. Seems like reduced behavior over what we already have.

2023-06-02 23:40 UTC, nicktobey approved these changes

2023-06-12 22:07 UTC, closed without merging