release: simplify homebrew bump job
dolthub/dolt pull request #6085
Opened 2023-06-02 18:39 UTC by chenrui333

not sure why, but currently the build does not quite work, https://github.com/dolthub/dolt/actions/runs/5158143131/jobs/9291442093

this PR is just to simplify the job (using the defaults by removing the redundant specifications), also the workflow_dispatch job can be totally replaced with `brew bump --open-pr dolt` (this is what i am doing with [this PR](https://github.com/Homebrew/homebrew-core/pull/132677))

2023-06-02 21:29 UTC, timsehn commented
Thanks for the contribution. I forget who is our Homebrew expert. I'll find him/her and have him/her review.

2023-06-02 23:13 UTC, timsehn commented
Looks like @coffeegoddd is all over the blame for this file. Assigning review to him.

2023-06-02 23:25 UTC, coffeegoddd requested changes
Thanks for the submission, a couple comments to address before we merge this.

2023-06-02 23:25 UTC, coffeegoddd commented on .github/workflows/cd-bump-homebrew.yaml
> -        required: true
we want to keep this, as sometimes we need to run the workflow manual after a release has already run.

2023-06-02 23:25 UTC, coffeegoddd commented on .github/workflows/cd-bump-homebrew.yaml
> -        required: true
you can dedupe the code by doing stuff like:
```
tag-name: ${{format('refs/tags/v{0}', github.event.client_payload.version || github.event.inputs.version)}}
```

where `github.event.client_payload.version` is from the `workflow_dispatch` event and `github.event.inputs.version` is from the `repository_dispatch` event.

2023-07-07 19:39 UTC, timsehn commented
Closing this one because contributor did not follow up.

2023-07-07 19:39 UTC, closed without merging