go: sqle/cluster: mysqldb_persister.go: Add exponential backoff to users and grants replication to avoid spamming logs.
dolthub/dolt pull request #6630
Opened 2023-09-07 21:31 UTC by reltuk

2023-09-08 21:53 UTC, timsehn requested changes
Jokes.

2023-09-08 21:53 UTC, timsehn requested changes
What? No jitter!

2023-09-08 21:53 UTC, timsehn commented on go/libraries/doltcore/sqle/cluster/controller.go
> +		bo.MaxElapsedTime = 0
Jitter please. Google is sad.

2023-09-11 18:06 UTC, timsehn approved these changes

2023-09-11 18:06 UTC, zachmu approved these changes
LGTM!

2023-09-11 18:06 UTC, zachmu commented on go/libraries/doltcore/sqle/cluster/mysqldb_persister.go
> +	backoff           backoff.BackOff
back off, man

back off, i said Back off!

2023-09-11 18:51 UTC, merged