migrates fetch to use sql queries
dolthub/dolt pull request #6652
Opened 2023-09-12 19:46 UTC by stephkyou

This change updates `dolt fetch` to use the appropriate sql engine to generate results.

Related: https://github.com/dolthub/dolt/issues/3922

2023-09-12 21:58 UTC, macneale4 requested changes
Lookin' good. A few minor things

2023-09-12 21:58 UTC, macneale4 commented on go/cmd/dolt/dolt.go
> +	if subcommandName == "fetch" || subcommandName == "pull" || subcommandName == "push" {
move down to line 628.

2023-09-12 21:58 UTC, macneale4 commented on go/cmd/dolt/commands/fetch.go
> +	writeToBuffer := func(s string) {
I think this function is simple enough that you could just use a strings.join() for this.

2023-09-12 21:58 UTC, macneale4 commented on integration-tests/bats/fetch.bats
> +    TMPDIRS=$(pwd)/tmpdirs
TMPDIRS is very close to the standard TMPDIR. How about FETCHROOT?

2023-09-12 21:58 UTC, macneale4 commented on integration-tests/bats/fetch.bats
> +@test "fetch: fetch main" {
This test isn't valid is there isn't a check for the absence of something. You should create another branch on the remote, and verify that it doesn't get fetched when you just fetch main.

2023-09-12 21:58 UTC, macneale4 commented on integration-tests/bats/fetch.bats
> +    dolt remote add test-remote file://../rem1
This remote should point to a remote that has different content. Then in tests which pull from `test-remote`, you can verify that you didn't fetch from origin.

2023-09-15 22:33 UTC, zachmu approved these changes
This looks pretty good, but the tests still need some work. You should have a different set of tables on the different remotes, or some other way to assert that you fetched the right one. Once you fix that you're good to go.

2023-09-15 22:33 UTC, zachmu commented on integration-tests/bats/fetch.bats
> +    run dolt sql -q "show tables as of hashof('origin/main')" -r csv
can just say `as of 'origin/main'` here

2023-09-15 22:33 UTC, zachmu commented on integration-tests/bats/fetch.bats
> +    [[ "$output" =~ "added table" ]] || false
This test has the same problem Neil pointed out: the assertions here look exactly the same as origin.

You need different contents in the thing you're fetching so you can be sure you got the right thing

2023-09-15 22:33 UTC, zachmu commented on integration-tests/bats/fetch.bats
> +    [[ "$output" =~ "Table" ]] || false
Same comment

It's not enough to just push / fetch different refs, the assertions need to rule out that you fetched a different one than you intended

2023-09-15 22:33 UTC, zachmu commented on integration-tests/bats/fetch.bats
> +    [[ "$output" =~ "Table" ]] || false
Same applies to all the tests below. Put a new commit / table on the thing you're fetching so you know you got the right thing

2023-09-16 00:56 UTC, merged