optimizations
dolthub/dolt pull request #888
Opened 2020-09-16 21:50 UTC by bheni

2020-10-02 22:10 UTC, bheni commented on go/libraries/doltcore/table/pipeline/procfunc_help.go
> -				// wake up and check stop condition
This creates a lot of garbage. select on the channel instead

2020-10-02 22:15 UTC, bheni commented on go/libraries/doltcore/sqle/rows.go
> +	var end types.LesserValuable
TupleValueSlice implements LesserValuable, but not Value

2020-10-03 00:21 UTC, bheni commented
@Hydrocharged would appreciate a look at FastNomsToSql in typeinfo.go

2020-10-03 00:55 UTC, bheni commented
Roughly a 40% performance improvement on a full table scan on the wikipedia-ngrams dataset:


```
Dataset: https://www.dolthub.com/repositories/Liquidata/wikipedia-ngrams
Command: GOMAXPROCS=1 time dolt --prof cpu  sql -r csv -q 'select bigram from bigram_counts' > out.csv

Before Changes:     1234.47 real      1186.96 user        19.17 sys
After Changes :      715.69 real       680.54 user        13.84 sys
```

2020-10-05 08:26 UTC, Hydrocharged requested changes
So there are a few errors I've spotted in the `FastNomsToSql` function, but I'm not a fan of the function in general. It looks like the goal is to reduce the time it takes to get a dolt value to a sql (go) value, which is the purpose of `ConvertNomsValueToValue`. Beforehand I was going through all of the conversion checks, which is unnecessary as everything stored will be valid, so no need to recheck every value (which is what `FastNomsToSql` is doing). In addition, the `TypeInfo` interface is meant to be as complete of an interface as possible, so I'd rather not have multiple locations to edit for when new types are added that adapt existing noms types.

Rather than ask you to remove `FastNomsToSql` and implement my feedback, I've made a PR that you can merge into yours! 😄 I was going to run the query that you posted above (before and after) to get an idea of the performance impact of my PR, but the ngrams dataset is downloading so slowly that it won't complete in a sane amount of time. If you wouldn't mind testing it on your machine then that would be great 😃

https://github.com/dolthub/dolt/pull/911

2020-10-05 18:24 UTC, bheni commented
@Hydrocharged I've merged your changes.

2020-10-06 01:03 UTC, Hydrocharged approved these changes
So I didn't run tests locally on my last PR, and I wasn't paying attention that only the formatting and license tests ran on Github (it just says All Checks Passed, didn't see the 2 under it), so it broke the tests that were relying on `ConvertNomsValueToValue` to do all the additional junk that's not being used (which should be in `IsValid` anyway). I fixed all of those tests here, and ran it locally since Github still isn't running the full suite of tests for the PR.

https://github.com/dolthub/dolt/pull/915

2020-10-07 20:43 UTC, merged